#!/usr/bin/python
import smtplib
import getpass
import sys

def prompt(prompt):
    return raw_input(prompt).strip()

fromaddr = prompt("From: ") if len(sys.argv) < 2 else sys.argv[1]
toaddrs  = prompt("To: ").split() if len(sys.argv) < 3 else sys.argv[2]
print "Enter message, end with ^D (Unix) or ^Z (Windows):"

# Add the From: and To: headers at the start!
msg = ("From: %s\r\nTo: %s\r\n\r\n"
       % (fromaddr, ", ".join(toaddrs)))
while 1:
    try:
        line = raw_input()
    except EOFError:
        break
    if not line:
        break
    msg = msg + "\n" + line

print "Message length is " + repr(len(msg))

server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
server.login(fromaddr, getpass.getpass())
#server.set_debuglevel(1)
server.sendmail(fromaddr, toaddrs, msg)
server.quit()
print "Sent successfully"
