#!/usr/bin/python

import sys
import os
from pygoogle import pygoogle

search_terms = sys.argv[1:-1]
search_text = ''
for word in search_terms:
    search_text = search_text + word + ' '
search = pygoogle(search_text)
search.display_results()

#clean up the folder
os.system('rm  ~/dev/scripts/*.pyc')
