#!/usr/bin/python

import os
import random
import sys

voices = file('/Users/ahoover/dev/scripts/voices.txt', 'r')

voice_list = []
for line in voices:
    voice_list.append(line[0:10])

what_to_say = ""
for i in range(1, len(sys.argv)):
    what_to_say = what_to_say + " " + sys.argv[i]
voice = voice_list[random.randint(0, len(voice_list)-1)]
os.system('say "'+ what_to_say + '" --voice=' + voice)
