#!/usr/bin/python
# This program will open the most recent skimm that there has been

import os

os.system('cd ~')
os.system('wget -q http://www.theskimm.com/archive')

f = file('archive', 'r')

state = 0
url = 'http://www.theskimm.com/'
for line in f:
    if state == 0 and  "Newsletter Archive" in line:
        state = 1
    elif state == 1:
        state = 2
    elif state == 2:
        url = url + line.split('"')[1]
        state = 3
    elif state == 3:
        break

os.system('rm archive')
os.system('open ' + url)
