#!/usr/bin/python
import poplib
from email import parser

f = file('skimm.html', 'w')

pop_conn = poplib.POP3_SSL('pop.gmail.com')
pop_conn.user('ahoover512@gmail.com')
pop_conn.pass_('Supermac101')

# Get messages
messages = [pop_conn.retr(1)] # latest skimm messages
#messages = [pop_conn.retr(i) for i in range(1, len(pop_conn.list()[1]) + 1)]

# Concat message pieces
messages = ["\n".join(mssg[1]) for mssg in messages]

# Parse message into email object
messages = [parser.Parser().parsestr(mssg) for mssg in messages]


for message in messages:
    for part in message.walk():
        f.write(part.get_payload())
pop_conn.quit()
